---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: gradle
    tag: 5.2.1-jdk8

inputs:
  - name: project
  - name: pipeline

outputs:
  - name: builds

run:
  path: /bin/bash
  user: root
  args:
    - pipeline/tasks/build.sh
 